## Introduction 
The article writes about 45 methods in NumPy that you should master to become a pro. This notebook is for practice of all the methods and codes described in the article

Article link - https://medium.com/geekculture/the-only-45-methods-you-should-master-to-become-a-numpy-pro-6ea77a8638a6

Soyinka Sowoolu
29th April 2023 

In [1]:
# Import the NumPy library and Pandas as well
import numpy as np
import pandas as pd 

ModuleNotFoundError: No module named 'numpy'

### (1-10) NumPy array creation methods 

**#1  NumPy array from a python list**

In [2]:
# Using the 'np.array()' method
a = [1, 2, 3]
np.array(a)

array([1, 2, 3])

In [3]:
# We can verify the datatype using the 'type()' method in python
type(np.array(a))

numpy.ndarray

In [4]:
# We can create a multi-dimensional array using a list of list e.g. 2 -dimensions as below
a = [[1, 2, 3], [3, 5, 6]]
np.array(a)

array([[1, 2, 3],
       [3, 5, 6]])

In [5]:
type(np.array(a))

numpy.ndarray

In [6]:
# To create a NumPy array of a specific type , pass the dtype argument
a = [[1, 2 ,3], [4,6,9]]
np.array(a,dtype = np.float32)

array([[1., 2., 3.],
       [4., 6., 9.]], dtype=float32)

**#2 Create a NumPy array of Zeros**

In [7]:
# This is done with the 'np.zeros()' method
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [8]:
# For multi-dimensional zeros array
np.zeros((3,9)) # not using a tuple will give a data type error

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**#3 Create a NumPy array of ones**

In [9]:
# This is done with the 'np.ones()' method
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
# For multi-dimensional array pass a tuple of the array shape e.g. 3-D
np.ones((4,6,7))

array([[[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]]])

**#4 Create an identity Numpy Array**

In [11]:
# This is an array where '1' are on the diagonal and others filled with '0' 

# This is done using the 'np.eye()' method
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**#5 Create an equally spaced array with a specific step skipped**

In [12]:
# This is created using the 'np.arange()' method
# Generate values from 0 -10 with 1 step
np.arange(0, 11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
# Generate without starting start point (defaults from 0 and steps 1)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# Generate from 5-11 step 2
np.arange(5, 11, 2)

array([5, 7, 9])

**#6 Create an equally spaced array with a specific array size**

In [15]:
# Generate n-nums (items) equally spaced within the interval defined using 'np.linspace(start=x, stop =y, num = n)'
np.linspace(2, 25, 10)

array([ 2.        ,  4.55555556,  7.11111111,  9.66666667, 12.22222222,
       14.77777778, 17.33333333, 19.88888889, 22.44444444, 25.        ])

**#7-8 Create a random NumPy array**

In [16]:
# Generate random array of integers
np.random.randint(low=5, high=16, size=5),np.random.randint(low=3, high=46, size=4)

(array([ 8, 15, 14,  9, 12]), array([17, 41,  5, 36]))

In [17]:
# Generate a random float sample
np.random.random(size = 10),np.random.random(7) # takes only one positional argument

(array([0.80540327, 0.56325764, 0.14439973, 0.76525774, 0.6328077 ,
        0.09542334, 0.19213061, 0.01946985, 0.84509799, 0.52635273]),
 array([0.04295742, 0.15090704, 0.01977598, 0.75971838, 0.23263461,
        0.24798641, 0.31336707]))

**#9-10 Generate NumPy array from Pandas Series**


In [18]:
# This can be done two ways. 1. using 'np.array()' 2. using 'np.asarray()'
s =pd.Series([1, 2, 3, 4, 5], name = 'col')
# method 1
np.array(s)


array([1, 2, 3, 4, 5], dtype=int64)

In [19]:
# method 2 
np.asarray(s)

array([1, 2, 3, 4, 5], dtype=int64)

### (11-21) NumPy array Manipulation methods 

**#11 Shape of the NumPy array**

In [20]:
# To determine the shape use 'np.shape()' method or the 'shape attribute of the ndarray'
a = np.ones((2,3))
print(f'The shape of the array- method 1 {np.shape(a)}')
print(f'The shape of the array- method 2 {a.shape}')

The shape of the array- method 1 (2, 3)
The shape of the array- method 2 (2, 3)


**#12 Reshape the NumPy array**

In [21]:
# This is giving a new shape to the array without altering its contents
# This is done using the 'np.reshape()' method
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**#13 -14 Transpose the NumPy Array**

In [23]:
# Tranposing an array (turning the rows to columns) is done using 'np.transpose()' or 'ndarray.T' 
a = np.arange(12).reshape(6,2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [24]:
# method 1
np.transpose(a)

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [25]:
# method 2
a.T

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

**#15-17 Concatenate multiple NumPy arrays to form one NumPy array**

In [26]:
# You use the 'np.concatenate()' method to join sequence of arrays and obtain new array
# Concatenate row-wise
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis =0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
b # We will need to transpose for the next operation

array([[5, 6]])

In [28]:
# Concatenate column-wise
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [29]:
# Concatenate to generate a flat NumPy array
np.concatenate((a,b),axis=None) 

array([1, 2, 3, 4, 5, 6])

**#18 Flatten NumPy Array**

In [30]:
# You can collapse the NumPy array into a single dimension using 'ndarray.flatten()'
a = np.array([[1, 2],[4, 8]])
a, a.flatten()

(array([[1, 2],
        [4, 8]]),
 array([1, 2, 4, 8]))

**#19 Unique elements of a NumPy Array**

In [31]:
# Use the 'np.unique()' method
a = np.array([[3, 4],[3, 8],[8, 4]])
np.unique(a)

array([3, 4, 8])

In [32]:
a

array([[3, 4],
       [3, 8],
       [8, 4]])

In [33]:
b

array([[5, 6]])

In [34]:
# unique rows
b = np.array([[1, 1, 3], [1, 1, 3], [2, 2, 3]])
np.unique(b,axis=0)

array([[1, 1, 3],
       [2, 2, 3]])

In [35]:
# Unique columns
np.unique(b,axis=1)

array([[1, 3],
       [1, 3],
       [2, 3]])

**#20 Squeeze a NumPy Array**

In [36]:
# You can remove axes of length one from your NumPy array, use the 'np.squeeze()' method'
x = np.array([[[0], [1], [2]]])
x

array([[[0],
        [1],
        [2]]])

In [37]:
x.shape

(1, 3, 1)

In [39]:
x_squeeze = np.squeeze(x)
x_squeeze

array([0, 1, 2])

In [40]:
x_squeeze.shape

(3,)

**#21 Transfrom NumPy array to Python list**

In [43]:
# Create a Python list from a NumPy array using the 'ndarray.tolist()' method
# define the NumPy array
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
a

array([[1, 1, 3],
       [1, 1, 3],
       [1, 1, 4]])

In [44]:
# Convert to a list
a.tolist()

[[1, 1, 3], [1, 1, 3], [1, 1, 4]]

### (22-33) Mathematical Operations on NumPy arrays**

**#22-24 Trigonometric Functions**

In [45]:
a = np.array([1, 2, 3])
print('Trigonometric Sine :', np.sin(a))
print('Trigonometric Cosine :', np.cos(a))
print('Trigonometric Tangent :', np.tan(a))


Trigonometric Sine : [0.84147098 0.90929743 0.14112001]
Trigonometric Cosine : [ 0.54030231 -0.41614684 -0.9899925 ]
Trigonometric Tangent : [ 1.55740772 -2.18503986 -0.14254654]


**#25-28 Rounding Functions**


You can use the following :

   *  return the element-wise floor using `np.floor()` method
   *  Return the element-wise ceiling using the `np.ceil()` method
   *  Round to the nearest integer using the `np.rint()` method


In [47]:
a = np.linspace(1, 2, 5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [48]:
np.floor(a)

array([1., 1., 1., 1., 2.])

In [50]:
np.ceil(a)

array([1., 2., 2., 2., 2.])

In [51]:
np.rint(a)

array([1., 1., 2., 2., 2.])

In [53]:
# round up to a given number of decimals using the `np.round()`
a = np.linspace(1, 2, 7)
np.round(a,2)

array([1.  , 1.17, 1.33, 1.5 , 1.67, 1.83, 2.  ])

**#29-30 Exponents and logarithms**


In [55]:
# Calculate the element-wise exponential using the `np.exp()` method
# Calculate the element-wise natural logarithm using the np.log() method

a = np.arange(1, 6)
a


array([1, 2, 3, 4, 5])

In [56]:
np.exp(a).round(2)

array([  2.72,   7.39,  20.09,  54.6 , 148.41])

In [57]:
np.log(a).round(2)

array([0.  , 0.69, 1.1 , 1.39, 1.61])

**#31-32 Sum and Product**

In [59]:
# Use the `np.sum()` to calculate the sum of array elements
a =np.array([[1, 2], [3, 4]])
np.sum(a)

10

In [60]:
# Sum the columns
np.sum(a, axis=1) 

array([3, 7])

In [61]:
# Sum the rows
np.sum(a, axis=0)

array([4, 6])

In [62]:
# Use the `np.prod()` to calculate the products of the elements
np.prod(a)

24

In [63]:
# Calculate the product of the columns
np.prod(a, axis=1)

array([ 2, 12])

In [65]:
# Calculate the product of the rows
np.prod(a, axis=0)

array([3, 8])

**#33 Square root**

In [66]:
# Use the `np.sqrt()` method
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [68]:
np.sqrt(a).round(3)

array([[1.   , 1.414],
       [1.732, 2.   ]])

### (34-36) Matrix and Vector Operations

**#34 Dot product**

In [69]:
# Use the `np.dot()` to calculate dot product of two arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np.dot(a,b)

array([[3, 3],
       [7, 7]])

**#35 Matrix Product**

In [70]:
# Use the `np.matmul()` to calculate dot product of two arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])
np.matmul(a, b)

array([[3, 3],
       [7, 7]])

The output of np.matmul() and np.dot() are the same for 1-D & 2-D matrices but not same for matrices N > 2

**#36 Vector Norm**

In [71]:
# The vector norm is used to calculate the length of a vector using `np.linalg.norm()`
a = np.arange(-4, 5)
np.linalg.norm(a) ## L2 Norm

7.745966692414834

In [72]:
np.linalg.norm(a, 1) ## L1 Norm

20.0

### (37-38) Sorting Methods

**#37 Sort a NumPy array**

In [73]:
# Sort the elements in the array using the `np.sort()` method
a = np.array([[1,4], [3, 1]])

In [80]:
# Sort each row (default)
np.sort(a)

array([[1, 4],
       [1, 3]])

In [81]:
# Sort the flattened array
np.sort(a, axis=None)

array([1, 1, 3, 4])

In [82]:
# Sort each column
np.sort(a, axis=0)

array([[1, 1],
       [3, 4]])

**#38 Order of indices in Sorted NumPy Array**

In [84]:
# To return the order of the matrix indices that will sort the array use `np.argsort()` method
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0], dtype=int64)

### (39-42) Searching Methods

**#39 Indices corresponding to maximum values**



In [85]:
# Use the `np.argmax()` method
a = np.random.randint(1, 20, 10).reshape(2,5)
a

array([[ 7,  9, 18,  3,  4],
       [ 6, 19,  1,  3,  7]])

In [86]:
# Max index in a flatten array
np.argmax(a)

6

In [87]:
# Max index along the column 
np.argmax(a, axis=0)

array([0, 1, 0, 0, 1], dtype=int64)

In [88]:
# Max index along the row

array([2, 1], dtype=int64)

In [89]:
# To get the index in a non-flattened array
ind = np.unravel_index(np.argmax(a),a.shape)
ind

(1, 1)

**#40 Indices corresponding to minimum values**

In [91]:
# Use the `np.argmin()`
a = np.random.randint(1, 20, 10).reshape(2, 5)
a

array([[ 1,  1,  6, 14,  9],
       [10,  4, 12, 18, 12]])

In [93]:
# Min index in a flatten array
np.argmin(a) 

0

In [94]:
# Min index along the column
np.argmin(a, axis=0)

array([0, 0, 0, 0, 0], dtype=int64)

In [95]:
# Min index along the row
np.argmin(a, axis=1)

array([0, 1], dtype=int64)

**#41 Search based on a condition**

In [97]:
# To select between two arrays based on a condition, use the `np.where()` method.
a = np.random.randint(-10, 10, 10)
a

array([-3, -6, -7,  1,  8,  2, -4, -9,  5,  9])

In [101]:
np.where(a <0, 0, a)
# '''
# if element < 0 
#     return 0
# else
#     return element

# '''

array([0, 0, 0, 1, 8, 2, 0, 0, 5, 9])

### (43-45) Statistical Methods

These are methods to compute standard descriptive statistics on NumPy

**#43 Mean**

In [109]:
# To find the mean along an axis use `np.mean()` method
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [104]:
# All the elements
np.mean(a)

2.5

In [105]:
# Mean along the columns
np.mean(a, axis=0)

array([2., 3.])

In [106]:
# Mean along the rows
np.mean(a, axis=1)

array([1.5, 3.5])

**#44 Median**

In [108]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [110]:
# Median of all elements
np.median(a)

2.5

In [111]:
# Median along the columns
np.median(a, axis=0)

array([2., 3.])

In [112]:
# Median along the rows
np.median(a, axis=1)

array([1.5, 3.5])

**#45 Standard Deviation**

In [113]:
# To compute the standard deviation of a NumPy array along a specified array use the `np.std()` method
a = np.array([[1, 2], [3, 4]])

In [114]:
# Standard deviation of all the elements
np.std(a)

1.118033988749895

In [115]:
# SD along the columns
np.std(a, axis=0)

array([1., 1.])

In [116]:
# SD along the rows
np.std(a, axis=1)

array([0.5, 0.5])