## Introduction 
The article writes about 45 methods in NumPy that you should master to become a pro. This notebook is for practice of all the methods and codes described in the article

Article link - https://medium.com/geekculture/the-only-45-methods-you-should-master-to-become-a-numpy-pro-6ea77a8638a6

Soyinka Sowoolu
29th April 2023 

In [1]:
# Import the NumPy library and Pandas as well
import numpy as np
import pandas as pd 

### (1-10) NumPy array creation methods 

**#1  NumPy array from a python list**

In [2]:
# Using the 'np.array()' method
a = [1, 2, 3]
np.array(a)

array([1, 2, 3])

In [4]:
# We can verify the datatype using the 'type()' method in python
type(np.array(a))

numpy.ndarray

In [5]:
# We can create a multi-dimensional array using a list of list e.g. 2 -dimensions as below
a = [[1, 2, 3], [3, 5, 6]]
np.array(a)

array([[1, 2, 3],
       [3, 5, 6]])

In [6]:
type(np.array(a))

numpy.ndarray

In [7]:
# To create a NumPy array of a specific type , pass the dtype argument
a = [[1, 2 ,3], [4,6,9]]
np.array(a,dtype = np.float32)

array([[1., 2., 3.],
       [4., 6., 9.]], dtype=float32)

**#2 Create a NumPy array of Zeros**

In [8]:
# This is done with the 'np.zeros()' method
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [13]:
# For multi-dimensional zeros array
np.zeros((3,9)) # not using a tuple will give a data type error

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**#3 Create a NumPy array of ones**

In [14]:
# This is done with the 'np.ones()' method
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
# For multi-dimensional array pass a tuple of the array shape e.g. 3-D
np.ones((4,6,7))

array([[[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]]])

**#4 Create an identity Numpy Array**

In [17]:
# This is an array where '1' are on the diagonal and others filled with '0' 

# This is done using the 'np.eye()' method
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**#5 Create an equally spaced array with a specific step skipped**

In [18]:
# This is created using the 'np.arange()' method
# Generate values from 0 -10 with 1 step
np.arange(0, 11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# Generate without starting start point (defaults from 0 and steps 1)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# Generate from 5-11 step 2
np.arange(5, 11, 2)

array([5, 7, 9])

**#6 Create an equally spaced array with a specific array size**

In [21]:
# Generate n-nums (items) equally spaced within the interval defined using 'np.linspace(start=x, stop =y, num = n)'
np.linspace(2, 25, 10)

array([ 2.        ,  4.55555556,  7.11111111,  9.66666667, 12.22222222,
       14.77777778, 17.33333333, 19.88888889, 22.44444444, 25.        ])

**#7-8 Create a random NumPy array**

In [23]:
# Generate random array of integers
np.random.randint(low=5, high=16, size=5),np.random.randint(low=3, high=46, size=4)

(array([10, 13,  9, 13, 15]), array([21,  9, 11, 36]))

In [27]:
# Generate a random float sample
np.random.random(size = 10),np.random.random(7) # takes only one positional argument

(array([0.15665669, 0.30359795, 0.61163921, 0.09512638, 0.67814708,
        0.45858923, 0.54702845, 0.81591304, 0.82327313, 0.90317709]),
 array([0.161783  , 0.28628223, 0.24013038, 0.80937222, 0.31845944,
        0.73119905, 0.47942951]))

**#9-10 Generate NumPy array from Pandas Series**


In [30]:
# This can be done two ways. 1. using 'np.array()' 2. using 'np.asarray()'
s =pd.Series([1, 2, 3, 4, 5], name = 'col')
# method 1
np.array(s)


array([1, 2, 3, 4, 5], dtype=int64)

In [29]:
# method 2 
np.asarray(s)

array([1, 2, 3, 4, 5], dtype=int64)

### (11-21) NumPy array Manipulation methods 

**#11 Shape of the NumPy array**

In [38]:
# To determine the shape use 'np.shape()' method or the 'shape attribute of the ndarray'
a = np.ones((2,3))
print(f'The shape of the array- method 1 {np.shape(a)}')
print(f'The shape of the array- method 2 {a.shape}')

The shape of the array- method 1 (2, 3)
The shape of the array- method 2 (2, 3)


**#12 Reshape the NumPy array**

In [40]:
# This is giving a new shape to the array without altering its contents
# This is done using the 'np.reshape()' method
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**#13 -14 Transpose the NumPy Array**

In [45]:
# Tranposing an array (turning the rows to columns) is done using 'np.transpose()' or 'ndarray.T' 
a = np.arange(12).reshape(6,2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [46]:
# method 1
np.transpose(a)

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [47]:
# method 2
a.T

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

**#15-17 Concatenate multiple NumPy arrays to form one NumPy array**

In [50]:
# You use the 'np.concatenate()' method to join sequence of arrays and obtain new array
# Concatenate row-wise
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis =0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
b # We will need to transpose for the next operation

array([[5, 6]])

In [52]:
# Concatenate column-wise
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [56]:
# Concatenate to generate a flat NumPy array
np.concatenate((a,b),axis=None) 

array([1, 2, 3, 4, 5, 6])

**#18 Flatten NumPy Array**

In [58]:
# You can collapse the NumPy array into a single dimension using 'ndarray.flatten()'
a = np.array([[1, 2],[4, 8]])
a, a.flatten()

(array([[1, 2],
        [4, 8]]),
 array([1, 2, 4, 8]))

**#19 Unique elements of a NumPy Array**

In [60]:
# Use the 'np.unique()' method
a = np.array([[3, 4],[3, 8],[8, 4]])
np.unique(a)

array([3, 4, 8])

In [61]:
a

array([[3, 4],
       [3, 8],
       [8, 4]])

In [69]:
b

array([[1, 1, 3],
       [1, 1, 3],
       [2, 2, 3]])

In [67]:
# unique rows
b = np.array([[1, 1, 3], [1, 1, 3], [2, 2, 3]])
np.unique(b,axis=0)

array([[1, 1, 3],
       [2, 2, 3]])

In [68]:
# Unique columns
np.unique(b,axis=1)

array([[1, 3],
       [1, 3],
       [2, 3]])